name: JS Actions

on: [push]

jobs:
  action:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: hello-action
      uses: ./.github/actions/hello-world
      with:
          first-greeting: "This message"
          second-greeting: "should be"
          third-greeting:  "Our message"
